### PR TITLE
Add "bretthayes" and preserve alphabetical order

### PR DESCRIPTION
**Pull request by bretthayes**
### What should this PR do?

- Adding myself as per Engineering specific onboarding
- Sorted the list of contributors in alphabetical order as per [the rule in the docs](https://docs.sourcegraph.com/dev/contributing/accepting_contribution#cla-bot)

### CODE REVIEW

**Comment by bretthayes** [comment]
> "This does not apply for Sourcegraph teammates."
– [The docs](https://docs.sourcegraph.com/dev/contributing/accepting_contribution#cla-bot)

@cla-bot check

**Comment by bretthayes** [comment]
@cla-bot check

**Review by indradhanush — APPROVED** [review]

**Comment by bretthayes** [comment]
@cla-bot check

**Comment by bretthayes** [comment]
@indradhanush I've signed the CLA but the check is still failing. Is there something I'm missing here or am I ok to merge since [this doesn't apply to SG teammates](https://docs.sourcegraph.com/dev/contributing/accepting_contribution#cla-bot)?

**Comment by indradhanush** [comment]
@bretthayes So this is a catch-22 situation. You need to have the CLA signed to make the check pass but you need to add your name so that future CLA checks pass. :joy: 

In the past I've authored PRs for new teammates so the check would pass in the PR. I think you're good to go ahead and merge this in this case.

**Pull request merged**
