### PR TITLE
Add subhash686 to clabot

### PR DESCRIPTION
**Pull request by subhash686**
I signed the CLA and noticed that the new proposed workflow is to let contributors make a clabot PR that a sourcegraph team member will approve.

Thanks!

### CODE REVIEW

**Comment by subhash686** [comment]
@sourcegraph/contribution-reviewers Signed CLA.

**Comment by subhash686** [comment]
@cla-bot check

**Comment by bobheadxi** [comment]
Closed by https://github.com/sourcegraph/clabot-config/pull/86

**Comment by bobheadxi** [comment]
Closed by https://github.com/sourcegraph/clabot-config/pull/86

**Comment by subhash686** [comment]
Any reason it's closed without merging? 
I have a sourcegraph pr waiting clabot verification. I signed CLA more than a month ago.
Please let me know. Thanks!

**Pull request closed without merging**
