### PR TITLE
Add Juneezee to .clabot

### PR DESCRIPTION
**Pull request by Juneezee**
CLA for contribution in this PR: https://github.com/sourcegraph/zoekt/pull/329

### CODE REVIEW

**Comment by Juneezee** [comment]
@cla-bot check

**Comment by Juneezee** [comment]
@cla-bot check

**Comment by Juneezee** [comment]
@cla-bot check

**Comment by Juneezee** [comment]
@cla-bot check

**Comment by bobheadxi** [comment]
Closed by https://github.com/sourcegraph/clabot-config/pull/86

**Pull request closed without merging**
